version: "3.7"
services:
  api:
    container_name: api
    build: ./api
    environment:
      PG_CONNECTION_STRING: postgres://admin:saSDaJnM@games_db:5432/games
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/usr/app/api/src


  db:
    container_name: games_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: saSDaJnM
      POSTGRES_USER: admin
      POSTGRES_DB: games
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432